name: af_weather
description: Flutter forecast project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:

  flutter_bloc: ^0.5.0
  http: ^0.12.0
  equatable: ^0.1.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  assets:
    - assets/
